{% set version = '0.1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-metalite.ae
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/metalite.ae_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/metalite.ae/metalite.ae_{{ version }}.tar.gz
  sha256: 505bf405e1951dae1cad9d1caa380ab089ff0a36b911fddd53f438e2acd9c86d

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-glue
    - r-metalite
    - r-r2rtf
  run:
    - r-base
    - r-glue
    - r-metalite
    - r-r2rtf

test:
  commands:
    - $R -e "library('metalite.ae')"           # [not win]
    - "\"%R%\" -e \"library('metalite.ae')\""  # [win]

about:
  home: https://merck.github.io/metalite.ae/, https://github.com/Merck/metalite.ae
  license: GPL-3.0-only
  summary: Analyzes adverse events in clinical trials using the 'metalite' data structure. The
    package simplifies the workflow to create production-ready tables, listings, and
    figures discussed in the adverse events analysis chapters of "R for Clinical Study
    Reports and Submission" by Zhang et al. (2022) <https://r4csr.org/>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
